import Link from "next/link";
import { CalculatorShell } from "@/components/calculators/calculator-shell";
import { CurtainMeasurementCalculator } from "@/components/calculators/decor-calculators";
import { createPageMetadata } from "@/lib/seo";

export const metadata = createPageMetadata({ title: "Curtain Measurement Calculator", description: "Calculate curtain rod width, fabric fullness, ready-made panel count, and finished drop from your window measurements.", path: "/calculators/curtain-measurement" });
const sourceClass = "font-semibold text-primary underline decoration-primary/35 underline-offset-4 outline-none focus-visible:ring-2 focus-visible:ring-ring";

export default function CurtainMeasurementPage() {
  return <CalculatorShell category="Window decoration calculator" title="Curtain Measurement Calculator" description="Plan an outside-mount rod, total curtain fullness, whole ready-made panel count, and finished drop using metric or imperial measurements." path="/calculators/curtain-measurement">
    <CurtainMeasurementCalculator />
    <article className="mt-14 grid gap-10 rounded-2xl bg-card-section p-5 sm:mt-16 sm:p-8 lg:p-10 xl:grid-cols-[minmax(0,1.1fr)_minmax(18rem,0.9fr)] xl:gap-12"><div className="space-y-10"><section><p className="text-xs font-bold tracking-[0.14em] text-primary uppercase">Ready-made panel estimate</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">Curtain measurement formula</h2><p className="mt-4 leading-7 text-muted-foreground">An outside-mount rod extends beyond both sides of the window. Fullness multiplies that complete rod width, and the panel count rounds up so the combined packaged width meets the target.</p><div className="mt-6 space-y-3 rounded-xl bg-card p-5 font-mono text-sm leading-6 shadow-sm"><p>Rod width = window width + (side extension × 2)</p><p>Total fabric width = rod width × fullness</p><p>Panels = round total width ÷ one panel width up</p></div></section><section><h2 className="text-3xl font-semibold tracking-tight">Measure the installed position</h2><p className="mt-4 leading-7 text-muted-foreground">Use the full rod length for panel width and measure the finished drop from the actual rod or ring position. Header type, rings, hems, pattern matching, fabric shrinkage, radiators, and floor clearance can change the final order.</p><p className="mt-4"><Link className={sourceClass} href="/guides/measuring-curtains">Read the curtain measuring guide</Link>.</p></section></div><aside className="space-y-5"><section className="rounded-xl bg-card p-5 shadow-sm"><h2 className="text-xl font-semibold">Source and review</h2><a className={`${sourceClass} mt-4 inline-flex`} href="https://www.homedepot.com/c/ah/how-to-measure-curtains/9ba683603be9fa5395fab90a2ca03be">Home Depot: How to measure curtains</a><p className="mt-4 text-sm leading-6 text-muted-foreground">The 23 cm / 9 in side-extension default reflects the guide&apos;s 8–10 in range. The 2× default sits within its 2–3× fullness guidance.</p></section><section className="rounded-xl bg-primary/10 p-5"><h2 className="text-xl font-semibold">Check the product</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Packaged width and length conventions differ. Confirm whether dimensions describe one panel or a pair and follow the rod and curtain manufacturer instructions.</p></section></aside></article>
  </CalculatorShell>;
}
