import Link from "next/link";
import { ApplianceRunningCostCalculator } from "@/components/calculators/appliance-running-cost-calculator";
import { CalculatorShell } from "@/components/calculators/calculator-shell";
import { FaqAccordion } from "@/components/marketing/faq-accordion";
import { applianceRunningCostAssumptions, applianceRunningCostExample, applianceRunningCostFaqs } from "@/data/appliance-running-cost";
import { appliancePresetSource } from "@/data/appliance-presets";
import { electricityRateReference, energySources } from "@/data/energy-reference";
import { formatUsd } from "@/lib/calculators/formatting";
import { createPageMetadata } from "@/lib/seo";

export const metadata = createPageMetadata({ title: "Appliance Running Cost Calculator", description: "Compare multiple appliances with 28 reference wattages, individual schedules, duty cycles and a combined monthly electricity cost table.", path: "/calculators/appliance-running-cost" });
const linkClass = "font-semibold underline underline-offset-4 rounded-sm focus-visible:ring-2 focus-visible:ring-ring";

export default function ApplianceRunningCostPage() {
  return <CalculatorShell category="Appliance inventory" description="Choose from 28 reference wattages, add several appliances, and compare their monthly costs. Adjust each schedule and duty cycle while keeping the assumptions visible." path="/calculators/appliance-running-cost" title="Appliance Running Cost Calculator">
    <ApplianceRunningCostCalculator />
    <article className="mt-12 max-w-4xl space-y-10 text-base leading-7">
      <section className="space-y-4"><h2 className="text-3xl font-semibold">Compare the loads you actually use</h2><p>A short-use appliance can draw more watts yet use less monthly energy than a small device that stays on. Build the list around a question: the devices in your home office, the appliances used during a damp month, or the extra loads you are considering. The table lets you compare them on the same rate without treating every device as a continuous load.</p><p>Choose a lookup entry to fill its name and wattage. The hours and days remain yours to set. Add another row for a different appliance or operating mode. You can rename rows to distinguish two similar devices. Remove a row to exclude it from the total; adding an unfinished row hides the total until its values are valid.</p><p>The lookup is a starting point. A generic refrigerator/freezer entry cannot represent every size, age or defrost system. If a model-specific energy label or a compatible meter gives you better evidence, use that instead. Electrical input watts belong in this calculation; microwave cooking output, cooling capacity and heating output do not.</p></section>
      <section className="space-y-4"><h2 className="text-3xl font-semibold">How duty cycle changes a row</h2><p>Duty cycle is the fraction of the scheduled time during which a load draws the entered on-cycle power. For example, a load observed running for half of a monitoring period has a 50% duty cycle. This simple model assumes no additional off-cycle power. A compressor, fan and defrost heater with different schedules will not be described perfectly by one percentage.</p><div className="rounded-xl bg-card p-5 font-mono text-sm"><p>Monthly kWh = watts ÷ 1,000 × hours/day × days/month × duty % ÷ 100</p><p className="mt-3">Monthly cost = monthly kWh × rate per kWh</p><p className="mt-3">Combined cost = sum of all row costs</p></div><p>Choose one approach. With on-cycle watts, enter the full observation window and the observed duty cycle. With average watts measured across that window, enter the same hours and leave duty at 100%. If you already shortened the hours to count only running time, leave duty at 100% too. Reducing both would undercount consumption.</p><p>The lookup source calls its values estimated average watts and does not establish a measured compressor-on rating. Selecting a preset therefore restores duty to 100%. Replace its wattage with verified on-cycle power before applying a separate cycling adjustment.</p></section>
      <section className="space-y-4"><h2 className="text-3xl font-semibold">Worked monthly comparison</h2><p>These are chosen planning schedules using the utility lookup&apos;s 1,500 W heater and 100 W laptop references. They are not measured household usage. The heater runs 3 hours daily and the laptop 8 hours daily, each for 30 days at 100% duty.</p><div className="overflow-x-auto rounded-xl border border-border"><table className="w-full text-left text-sm"><caption className="p-3 text-left">At the US average residential rate of $0.1834/kWh for June 2026, per <a href={electricityRateReference.url} className={linkClass}>EIA</a></caption><thead><tr><th scope="col" className="p-3">Appliance</th><th scope="col" className="p-3">kWh/month</th><th scope="col" className="p-3">Cost/month</th></tr></thead><tbody><tr className="border-t border-border"><th scope="row" className="p-3">Heater</th><td className="p-3">135</td><td className="p-3">{formatUsd(applianceRunningCostExample.monthlyCost)}</td></tr><tr className="border-t border-border"><th scope="row" className="p-3">Laptop</th><td className="p-3">24</td><td className="p-3">{formatUsd(24 * electricityRateReference.rate)}</td></tr><tr className="border-t border-border font-semibold"><th scope="row" className="p-3">Total</th><td className="p-3">159</td><td className="p-3">{formatUsd(159 * electricityRateReference.rate)}</td></tr></tbody></table></div><p>The heater calculation is 1.5 × 3 × 30 = 135 kWh. The laptop calculation is 0.1 × 8 × 30 = 24 kWh. Together they use 159 kWh in this scenario, costing {formatUsd(159 * electricityRateReference.rate)}. The total uses unrounded row values, so displayed rounded rows can occasionally differ from the total by a cent.</p><p>Changing an assumption changes the estimate, not the appliance. A different duty cycle does not promise a saving. Seasonal equipment also needs a seasonal schedule; multiplying a busy month by 12 can overstate a year.</p></section>
      <section className="space-y-4"><h2 className="text-3xl font-semibold">Assumptions and limits</h2><ul className="list-disc space-y-3 pl-6">{applianceRunningCostAssumptions.map((item) => <li key={item}>{item}</li>)}</ul><p>Use the <Link className={linkClass} href="/guides/appliance-energy-use">appliance measurement guide</Link> to choose a wattage basis. For separate peak and off-peak rates, calculate each period independently using the <Link className={linkClass} href="/calculators/electricity-cost">Electricity Cost Calculator</Link>; this inventory shares one rate across every row. The <Link className={linkClass} href="/guides/electricity-costs">tariff guide</Link> explains how to choose that rate.</p></section>
      <section><h2 className="text-3xl font-semibold">Appliance inventory questions</h2><FaqAccordion className="mt-6 border-y border-border" items={applianceRunningCostFaqs} /></section>
      <section className="space-y-4"><h2 className="text-3xl font-semibold">Sources and review</h2><ul className="list-disc space-y-2 pl-6"><li><a className={linkClass} href={appliancePresetSource.url}>{appliancePresetSource.title}</a>: all lookup wattages, described by the source as estimated averages.</li><li><a className={linkClass} href={electricityRateReference.url}>EIA table 5.6.A</a>: June 2026 US residential rate.</li><li><a className={linkClass} href={energySources.eiaUnits}>EIA: measuring electricity</a>: power and energy units.</li><li><a className={linkClass} href={energySources.ftc}>FTC: using EnergyGuide labels</a>: standardized estimates and local usage.</li></ul><p className="text-sm">Reviewed September 7, 2026. Read the <Link className={linkClass} href="/disclaimer">estimate disclaimer</Link>. Follow product instructions for measurement equipment and ask a licensed electrician about hardwired loads or electrical safety.</p></section>
    </article>
  </CalculatorShell>;
}
